#! /usr/bin/env bash

PREFIX=${PREFIX:-$PWD/local}
BASE=$PWD
SHERPA_VERSION=${SHERPA_VERSION:-2.2.16}

# TODO: check for rsync, scons and pypy3
# TODO: update Sherpa to CMake build with v3
# TODO: check for libtool, texinfo, texlive-metapost, feynmf, libsqlite3-dev, swig, openmpi-bin, libopenmpi-dev

cd $PREFIX
git clone https://gitlab.com/openloops/OpenLoops.git 
cd OpenLoops
./scons
./openloops libinstall ppln ppln_ew pptt

PATH=$PATH:/usr/lib64/openmpi/bin
cd $BASE
git clone -b v${SHERPA_VERSION} https://gitlab.com/sherpa-team/sherpa.git
cd sherpa
autoreconf -fi
./configure \
  --prefix=$PREFIX \
  --enable-{lhapdf,fastjet,hepmc3,openloops,rivet}=$PREFIX \
  --enable-analysis --disable-pyext --enable-gzip --enable-mpi CC=mpicc CXX=mpic++
make -j $(nproc --ignore=1) CXXFLAGS="-O2" AM_CXXFLAGS="-O2"
make install
mkdir $PREFIX/Sherpa && mv Examples /usr/local/Sherpa
