#! /usr/bin/env bash

PREFIX=${PREFIX:-$PWD/local}
BASE=$PWD
PYTHIA_VERSION=${PYTHIA_VERSION:-8313}

# TODO: check for fastjet,rivet,hepmc3? All should be installed by rivet-bootstrap, so we shouldn't have to bother

## Check for LHAPDF
if [[ -z "$(ls $PREFIX/lib/libLHAPDF.*)" ]]; then
    echo "No libLHAPDF found in $PREFIX. Please install it either manually or by passing INSTALL_LHAPDF=1 to rivet-bootstrap. Aborting..." 1&>2
    exit 2
fi

wget --no-verbose https://pythia.org/download/pythia83/pythia${PYTHIA_VERSION}.tgz -O- | tar xz
cd pythia*/
./configure --{prefix,with-{hepmc3,lhapdf6,rivet}}=$PREFIX --with-gzip
make -j $(nproc --ignore=1) && make install
cd examples
for i in 144 164; do
    make main$i
    cp main$i $PREFIX/bin/pythia8-main$i
done
