#! /usr/bin/env bash

PREFIX=${PREFIX:-$PWD/local}
BASE=$PWD
SHERPA_VERSION=${SHERPA_VERSION:-2.2.16}
SHERPA_VERSION=${SHERPA_VERSION:-3.0.1}

# TODO: check for rsync, scons and pypy3
# TODO: update Sherpa to CMake build with v3
# TODO: check for libtool, texinfo, texlive-metapost, feynmf, libsqlite3-dev, swig, openmpi-bin, libopenmpi-dev

## Check for LHAPDF
if [[ -z "$(ls $PREFIX/lib/libLHAPDF.*)" ]]; then
    echo "No libLHAPDF found in $PREFIX. Please install it either manually or by passing INSTALL_LHAPDF=1 to rivet-bootstrap. Aborting..." 1&>2
    exit 2
fi

## Install OpenLoops
cd $PREFIX
git clone https://gitlab.com/openloops/OpenLoops.git 
cd OpenLoops
./scons
./openloops libinstall ppln ppln_ew pptt

## Try to put OpenMPI in scope
if [[ "${ENABLE_MPI:-0}" = 1 ]]; then
    PATH=$PATH:/usr/lib64/openmpi/bin  #< TODO: make this (from Ubuntu Docker) more portable/robust... or leave to the user
    export CC=mpicc
    export CXX=mpic++
else
    NO_MPI=1  #< define variable to block MPI flag-substs below
fi

## Get Sherpa code
cd $BASE
git clone -b v${SHERPA_VERSION} https://gitlab.com/sherpa-team/sherpa.git
cd sherpa

## Build and install, with different systems for v2.x and v3.x
if [[ ${SHERPA_VERSION} =~ ^3\. ]]; then
    ## New 3.x series
    mkdir _BUILD
    cmake -S . -B _BUILD -DCMAKE_INSTALL_PREFIX=$PREFIX \
          -DRIVET_DIR=$PREFIX -DHEPMC3_DIR=$PREFIX \
          ${NO_MPI:-"-DSHERPA_ENABLE_MPI=ON"}
    cmake --build _BUILD  -j $(nproc --ignore=1)
    cmake --install _BUILD
else
    ## Old 2.x series (remove at some point, when fully mainstream)
    autoreconf -fi
    ./configure \
        --prefix=$PREFIX \
        --enable-{lhapdf,fastjet,hepmc3,openloops,rivet}=$PREFIX \
        --enable-analysis --disable-pyext --enable-gzip \
        ${NO_MPI:-"--enable-mpi"}
    make -j $(nproc --ignore=1) CXXFLAGS="-O2" AM_CXXFLAGS="-O2"
    make install
    mkdir -p $PREFIX/share/SHERPA-MC && cp -r Examples $PREFIX/share/SHERPA-MC/
fi
