#! /usr/bin/env bash

## Boost and GSL are expected to be installed correctly, as is a sane suite of GNU build tools

test -z "$BUILD_PREFIX" && BUILD_PREFIX="$PWD"
test -z "$INSTALL_PREFIX" && INSTALL_PREFIX="$PWD/local"
test -z "$MAKE" && MAKE="make -j3"

test -z "$RIVET_VERSION" && RIVET_VERSION="2.3.0"
test -z "$YODA_VERSION" && YODA_VERSION="1.5.0"

test -z "$RIVET_CONFFLAGS" && RIVET_CONFFLAGS="" #--enable-unvalidated
test -z "$YODA_CONFFLAGS" && YODA_CONFFLAGS=""

## Disable asserts for production running
export CPPFLAGS="$CPPFLAGS -DNDEBUG"


###############

echo "Running Rivet 2.x bootstrap script with LCG HepMC, FastJet and Boost"
echo "Building Rivet $RIVET_VERSION, YODA $YODA_VERSION"

## Immediate exit on a command (group) failure and optional debug mode
set -e
test -n "$DEBUG" && set -x
export PATH=$INSTALL_PREFIX/bin:$PATH

function wget_untar { wget --no-check-certificate $1 -O- | tar xz; }
function conf { ./configure --prefix=$INSTALL_PREFIX "$@"; }
function mmi { $MAKE "$@" && $MAKE install; }


## Make installation directory, with an etc subdir so Rivet etc. will install bash completion scripts
mkdir -p $INSTALL_PREFIX/etc/bash_completion.d


## Define LCG platform etc. -- may need to be customised
LCGTAG="x86_64-slc6-gcc48-opt"
LCGVERSION="LCG_79"
LCGDIR="/afs/cern.ch/sw/lcg/releases/$LCGVERSION"
test -d "$LCGDIR" || { echo "LCG AFS filesystem not found: exiting..." 1>&2 ; exit 1; }
## Setup GCC
SETUPCMD_GCC="source $LCGDIR/gcc/4.8.4/x86_64-slc6/setup.sh"
$SETUPCMD_GCC
## Setup Python
SETUPCMD_PYTHON="source $LCGDIR/Python/2.7.9.p1/x86_64-slc6-gcc48-opt/Python-env.sh"
$SETUPCMD_PYTHON

## Add local dirs to the paths
PATH=$INSTALL_PREFIX/bin:$PATH
LD_LIBRARY_PATH=$INSTALL_PREFIX/lib:$LD_LIBRARY_PATH
PYTHONPATH=$INSTALL_PREFIX/lib64/python2.7/site-packages:$PYTHONPATH


## LCG locations of standard HEP libraries
HEPMCPATH=$LCGDIR/HepMC/2.06.09/$LCGTAG
FASTJETPATH=$LCGDIR/fastjet/3.1.1/$LCGTAG
BOOSTPATH=$LCGDIR/Boost/1.55.0_python2.7/$LCGTAG


## Install YODA
echo; echo "Building YODA"
cd $BUILD_PREFIX
test -d YODA-$YODA_VERSION || wget_untar http://www.hepforge.org/archive/yoda/YODA-$YODA_VERSION.tar.gz
cd YODA-$YODA_VERSION
conf $YODA_CONFFLAGS --with-boost=$BOOSTPATH
mmi
> $INSTALL_PREFIX/yodaenv.sh
## Install setup script with GCC/Python env if on AFS
if [[ "$USE_LCGAFS" = 1 ]]; then
    echo "source $GCCSETUP" >> $INSTALL_PREFIX/yodaenv.sh
    echo "PATH=$PYTHONBIN:\$PATH" >> $INSTALL_PREFIX/yodaenv.sh
fi
cat yodaenv.sh >> $INSTALL_PREFIX/yodaenv.sh


## Install Rivet
echo; echo "Building Rivet"
cd $BUILD_PREFIX
test -d Rivet-$RIVET_VERSION || wget_untar http://www.hepforge.org/archive/rivet/Rivet-$RIVET_VERSION.tar.gz
cd Rivet-$RIVET_VERSION
conf $RIVET_CONFFLAGS --with-yoda=$INSTALL_PREFIX \
  --with-hepmc=$HEPMCPATH --with-fastjet=$FASTJETPATH --with-boost=$BOOSTPATH
mmi
> $INSTALL_PREFIX/rivetenv.sh
## Install setup script with GCC/Python env if on AFS
if [[ "$USE_LCGAFS" = 1 ]]; then
    echo "source $GCCSETUP.sh" >> $INSTALL_PREFIX/rivetenv.sh
    echo "PATH=$PYTHONBIN:\$PATH" >> $INSTALL_PREFIX/rivetenv.sh
fi
cat rivetenv.sh >> $INSTALL_PREFIX/rivetenv.sh


## Make a top-level environment setup script
> $INSTALL_PREFIX/env.sh
echo $SETUPCMD_GCC >> $INSTALL_PREFIX/env.sh
echo $SETUPCMD_PYTHON >> $INSTALL_PREFIX/env.sh
echo "source $INSTALL_PREFIX/yodaenv.sh" >> $INSTALL_PREFIX/env.sh
echo "source $INSTALL_PREFIX/rivetenv.sh" >> $INSTALL_PREFIX/env.sh


## Announce the build success
echo; echo "All done. Now set some variables in your shell by sourcing $INSTALL_PREFIX/env.(c)sh"
