#! /usr/bin/env bash


## Function to unpack and delete a tarball
wget-untargz() {
    ## Try first using wget, and falling back to trying curl (for Mac)
    WGETTER="wget --quiet -O-"
    if test ! -x "`which wget 2> /dev/null`"; then
        WGETTER="curl --silent"
        if test ! -x "`which curl 2> /dev/null`"; then
            echo "You need curl or wget to download the $tarname tarball" 1>&2
            exit 1
        fi
    fi
    ## Use whichever was present
    $WGETTER $1 | tar xzv
}


##############################


## If we've got SVN and there are no already-checked out versions
## of AGILe and Rivet in this directory, then check out/update
## the SVN head versions using the HTTP access method
if test -x "`which svn 2> /dev/null`"; then
    if test -d agile; then (cd agile; svn up); else svn co http://svn.hepforge.org/agile/trunk agile; fi
    if test -d rivet; then (cd rivet; svn up); else svn co http://svn.hepforge.org/rivet/trunk rivet; fi
else
    echo "Couldn't get AGILe and rivet via svn" 1>&2
fi

## Get LHAPDF
LHAPDFNAME=lhapdf-5.3.0 
test -d $LHAPDFNAME || wget-untargz http://www.hepforge.org/archive/lhapdf/$LHAPDFNAME.tar.gz

## Get HepMC
HEPMCNAME=HepMC-2.03.03
test -d $HEPMCNAME || wget-untargz http://lcgapp.cern.ch/project/simu/HepMC/download/$HEPMCNAME.tar.gz

## Get FastJet
FASTJETNAME=fastjet-2.3.0
test -d $FASTJETNAME || wget-untargz http://www.lpthe.jussieu.fr/~salam/repository/software/fastjet/$FASTJETNAME.tar.gz

## Get Fortran Herwig
test -d herwig-6.507 || wget-untargz http://www.hepforge.org/archive/cedar/herwig-6.507.tar.gz
test -d herwig-6.510 || wget-untargz http://www.hepforge.org/archive/cedar/herwig-6.510.tar.gz

## Get Fortran Pythia
test -d pythia-6.326 || wget-untargz http://www.hepforge.org/archive/cedar/pythia-6.326.tar.gz
test -d pythia-6.411 || wget-untargz http://www.hepforge.org/archive/cedar/pythia-6.411.tar.gz

## Get Jimmy (for FHerwig)
test -d jimmy-4.31 || wget-untargz http://www.hepforge.org/archive/jimmy/jimmy-4.31.tar.gz


###############


## Function to enter an expanded tarball and run the usual
## autotools ./configure, make, make install mantra
conf-mk-mkinst() {
    if test -d $1; then 
        (cd $1 && echo "./configure --prefix=$PREFIX" && ./configure --prefix=$PREFIX && make && make install)
    else
        echo "Couldn't find $1... exiting"
        exit 1
    fi
}

## Build and install to the PREFIX location
PREFIX=$PWD/local
test $# -eq 1 && PREFIX=$1
mkdir -p $PREFIX
if test -w "$PREFIX" -a -d "$PREFIX"; then
    conf-mk-mkinst $HEPMCNAME
    conf-mk-mkinst $LHAPDFNAME
    conf-mk-mkinst $FASTJETNAME

    ## TODO: convert to Genser packages
    #conf-mk-mkinst herwig-6.507
    conf-mk-mkinst herwig-6.510
    conf-mk-mkinst pythia-6.326
    conf-mk-mkinst pythia-6.411
    conf-mk-mkinst jimmy-4.31

    ## Build and install RivetGun
    if test -d agile; then
        (cd agile && autoreconf -i)
        conf-mk-mkinst agile 
    else
        echo "AGILe build directory is not available"
    fi

    ## Build and install Rivet
    if test -d rivet; then
    (cd rivet && autoreconf -i)
    conf-mk-mkinst rivet
    else
        echo "Rivet build directory is not available"
    fi
else
    echo "Problem! PREFIX directory ($PREFIX) is not writeable" 1>&2
fi
